//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppDigitalCv.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class catAlergias
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public catAlergias()
        {
            this.tblAlergiasPersonal = new HashSet<tblAlergiasPersonal>();
        }
    
        public int idAlergias { get; set; }
        public string strDescripcion { get; set; }
        public string strObservacion { get; set; }
        public int idTipoAlergia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAlergiasPersonal> tblAlergiasPersonal { get; set; }
        public virtual catTipoAlergias catTipoAlergias { get; set; }
    }
}
