//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppDigitalCv.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class catFamiliar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public catFamiliar()
        {
            this.tblPersonal = new HashSet<tblPersonal>();
        }
    
        public int idFamiliar { get; set; }
        public string strNombre { get; set; }
        public string strOcupacion { get; set; }
        public string strDomicilio { get; set; }
        public int intEdad { get; set; }
        public bool bitVive { get; set; }
        public Nullable<System.DateTime> dteFechaNacimiento { get; set; }
        public int idParentesco { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPersonal> tblPersonal { get; set; }
        public virtual catParentesco catParentesco { get; set; }
    }
}
