//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppDigitalCv.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDatosLaboralesAdministrativos
    {
        public int idDatosLaboralesAdministrativos { get; set; }
        public int idArea { get; set; }
        public int idTipoContrato { get; set; }
        public int idPersonal { get; set; }
        public int idUnidadesAcademicas { get; set; }
        public Nullable<System.DateTime> dteFechaNombramientoConsejo { get; set; }
        public Nullable<System.DateTime> dteFechaInicioUttt { get; set; }
        public Nullable<System.DateTime> dteFechaRegistro { get; set; }
    
        public virtual catArea catArea { get; set; }
        public virtual catTipoContrato catTipoContrato { get; set; }
        public virtual catUnidadesAcademicas catUnidadesAcademicas { get; set; }
        public virtual tblPersonal tblPersonal { get; set; }
    }
}
