//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppDigitalCv.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDeportePersonal
    {
        public int idDeperotePersonal { get; set; }
        public int idDeporte { get; set; }
        public int idPersonal { get; set; }
        public Nullable<System.DateTime> dteFechaRegistro { get; set; }
        public int idFrecuencia { get; set; }
    
        public virtual catDeporte catDeporte { get; set; }
        public virtual catFrecuencia catFrecuencia { get; set; }
        public virtual tblPersonal tblPersonal { get; set; }
    }
}
