//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppDigitalCv.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblIdiomaDialectoPersonal
    {
        public int idIdiomaDialectoPersonal { get; set; }
        public Nullable<int> idIdioma { get; set; }
        public Nullable<int> idDialecto { get; set; }
        public int idPersonal { get; set; }
        public string strComunicacionPorcentaje { get; set; }
        public string strEscrituraProcentaje { get; set; }
        public string strEntendimientoPorcentaje { get; set; }
        public string strLecturaPorcentaje { get; set; }
        public Nullable<System.DateTime> dteFechaRegistro { get; set; }
    
        public virtual catDialecto catDialecto { get; set; }
        public virtual catIdioma catIdioma { get; set; }
        public virtual tblPersonal tblPersonal { get; set; }
    }
}
