//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppDigitalCv.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPremiosDocente
    {
        public int idPersonal { get; set; }
        public int idDocumento { get; set; }
        public Nullable<System.DateTime> dteFechaObtencionPremio { get; set; }
        public string strInstitucion { get; set; }
        public string strNombrePremio { get; set; }
        public string strActividadDesempeniada { get; set; }
        public Nullable<System.DateTime> dteFechaInicioPremio { get; set; }
        public Nullable<System.DateTime> dteFechaFinPremio { get; set; }
        public string strTipoPremio { get; set; }
    
        public virtual catDocumentos catDocumentos { get; set; }
        public virtual tblPersonal tblPersonal { get; set; }
    }
}
